### ISSUE TITLE
Secure?

### ISSUE THREAD

**Issue by jayceslesar** [TeddiO/pySteamSignIn#14]
How is this secure at all? Looking at the examples, they all just take the request params which are redirect params. Anybody could just send a request to the redirect endpoint with correct-ish params and the validate would return true

**Comment by TeddiO** [comment]
A little bit of adversarial issue to open, but essentially:

1) We send the user to Steam (`https://steamcommunity.com/openid/login`) specifying the spec we're using (`http://specs.openid.net/auth/2.0`) and the URL we want to be returned to.
2) Steam send back a number of things, including details that they want us to send back to them https://github.com/TeddiO/pySteamSignIn/blob/5e6f982a79121956ea7e48323f20d7dd596163ed/pysteamsignin/steamsignin.py#L97-L101 to help Steam verify the request. 
3) We send a request back to Steam (`https://github.com/TeddiO/pySteamSignIn/blob/5e6f982a79121956ea7e48323f20d7dd596163ed/pysteamsignin/steamsignin.py#L113C1-L119C83`) with `validationArgs['openid.mode'] = 'check_authentication'` asking them to check and validate what we've sent. Note we only ever dial out to Steam via `self._provider` which is `https://steamcommunity.com/openid/login`.
4) Steam sends a response with the details.

If at any point you send a forged response, Steam will always reject it from their side meaning we'll always return `False`. However that's how effectively the OpenID 2.0 spec works - the provider (Steam) should always be validating what we're sending.

If there's any pointers or constructive criticism, I'm happy to take it on board.

**Comment by jayceslesar** [comment]
Yeah the confusion comes from https://github.com/TeddiO/pySteamSignIn/blob/master/samples/fastapi-sample.py#L22 where the user could just hit that endpoint with bum data in the request params no?

**Comment by TeddiO** [comment]
So it's true they could hit the endpoint with bad data, but it's always going to fail verification because it *always* validates with Steam. If we didn't validate with Steam and accepted client input for the endpoint URL then sure. That's why we always ensure we're talking to Steam with data (I.E.  `self._provider`) we control, never that a client can manipulate.

It's not unreasonable to say that we could always check the origin is one from Steam to reduce potential CPU usage, but that's probably about it. It's worth mentioning that this is generally how OAuth works as well (but has the ability to pass through 'claims' and so on).

**Comment by jayceslesar** [comment]
Sweet, thanks for the clarification here, feel free to close/change title
