### ISSUE TITLE
Quart(Async) Support

### ISSUE THREAD

**Issue by emre-ozel** [TeddiO/pySteamSignIn#5]
Dear Contributors ,

Is there any chance that you implement functionality of library to [Quart](https://pgjones.gitlab.io/quart/), which uses the same apis as  flask, but is an asyncio reimplementation?

**Comment by TeddiO** [comment]
Do you mean as a helper function? There's no plans at the moment to extend the helper functions.

Feel free to open a PR though!

**Comment by emre-ozel** [comment]
I mean the function (redirecting the user and receiving the user's steam id ) for the Quart microframework, which is very similar to Flask.

**Comment by TeddiO** [comment]
So the redirection function is just there to be used as a useful utility and isn't actually required - there's nothing stopping you from crafting the request outside out of the library and redirecting the user accordingly. There's also no i/o blocking so it doesn't really benefit from being async anyhow. 

The SteamID verification process _would_ benefit from async but again I don't really have any future plans to migrate this however you could possibly wrap it in [run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) to get async-like behaviour.

**Comment by emre-ozel** [comment]
> Feel free to open a PR though!

What do you mean by "opening PR"?

**Comment by TeddiO** [comment]
So a PR is a Pull Request and allows you to write code and submit it as a possible change to this repository! More details can be found [here](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) in GitHubs own docs. 

As an example, a PR this repo has seen before is this one - https://github.com/TeddiO/pySteamSignIn/pull/3 , where extreme4all  wanted this module available on pypi / pip and did the main legwork to get it added.

PRs allow for collaboration and means that if you feel there's an improvement to be made - you can do a chunk of the legwork and then propose it! Understandably there's an element of you have to be comfortable writing code but due to the nature of PRs it allows you to receive feedback to get any PR to the best possible place.

**Comment by emre-ozel** [comment]
I thought it was the short form of **P**ublic **R**elations. Got it. Thanks!
